//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *OTelCollector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OTelCollector) DeepCopy() *OTelCollector {
	if in == nil {
		return nil
	}
	out := new(OTelCollector)
	in.DeepCopyInto(out)
	return out
}

func (in *OTelCollector) DeepCopyInto(out *OTelCollector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *OTelCollectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OTelCollectorList) DeepCopy() *OTelCollectorList {
	if in == nil {
		return nil
	}
	out := new(OTelCollectorList)
	in.DeepCopyInto(out)
	return out
}

func (in *OTelCollectorList) DeepCopyInto(out *OTelCollectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OTelCollector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OTelCollectorSpec) DeepCopyInto(out *OTelCollectorSpec) {
	*out = *in
	out.Pipeline = in.Pipeline
	in.Sampling.DeepCopyInto(&out.Sampling)
	out.StoreAndForward = in.StoreAndForward
}

func (in *OTelCollectorSpec) DeepCopy() *OTelCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(OTelCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OTelCollectorStatus) DeepCopyInto(out *OTelCollectorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcileTime != nil {
		t := *in.LastReconcileTime
		out.LastReconcileTime = &t
	}
}

func (in *OTelCollectorStatus) DeepCopy() *OTelCollectorStatus {
	if in == nil {
		return nil
	}
	out := new(OTelCollectorStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PipelineSpec) DeepCopyInto(out *PipelineSpec) { *out = *in }

func (in *PipelineSpec) DeepCopy() *PipelineSpec {
	if in == nil {
		return nil
	}
	out := new(PipelineSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SamplingSpec) DeepCopyInto(out *SamplingSpec) {
	*out = *in
	if in.TailPolicies != nil {
		in, out := &in.TailPolicies, &out.TailPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *SamplingSpec) DeepCopy() *SamplingSpec {
	if in == nil {
		return nil
	}
	out := new(SamplingSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StoreAndForwardSpec) DeepCopyInto(out *StoreAndForwardSpec) { *out = *in }

func (in *StoreAndForwardSpec) DeepCopy() *StoreAndForwardSpec {
	if in == nil {
		return nil
	}
	out := new(StoreAndForwardSpec)
	in.DeepCopyInto(out)
	return out
}
